# Generated by Django 3.0.4 on 2020-03-25 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefectures', models.CharField(blank=True, choices=[('北海道', '北海道'), ('青森', '青森'), ('秋田', '秋田')], max_length=50)),
                ('works', models.CharField(blank=True, choices=[('エンジニア', 'エンジニア'), ('農業関係', '農業関係')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
