# Generated by Django 3.0.4 on 2020-04-15 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inovationapp', '0002_auto_20200415_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='content',
            field=models.TextField(max_length=300),
        ),
    ]
